language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  
install: "pip install -r requirements.txt"

script: 
  - python a.py
